In [ ]:
!pip install git+https://github.com/d2l-ai/d2l-zh@release  # installing d2l

显示GPU

In [3]:
!nvidia-smi

Wed Aug 11 14:29:12 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

计算设备

In [4]:
import torch
from torch import nn

torch.device('cpu'),torch.cuda.device('cuda'),torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x7f83cada3a50>)

查询可用gpu的数量

In [5]:
torch.cuda.device_count()

1

这两个函数允许我们在请求的GPU不存在的情况下运行代码

In [6]:
def try_gpu(i=0):
    """如果存在，则返回gpu(i)，否则返回cpu()。"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]。"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

查询张量所在的设备

In [7]:
x=torch.tensor([1,2,3])
x.device

device(type='cpu')

存储在GPU上

In [8]:
X=torch.ones(2,3,device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

计算

In [9]:
X-1

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [10]:
X.cuda(0) is X

True

神经网络与GPU

In [11]:
net=nn.Sequential(nn.Linear(3,1))
net=net.to(device=try_gpu())

net(X)

tensor([[0.5584],
        [0.5584]], device='cuda:0', grad_fn=<AddmmBackward>)

确认一个模型参数存储在同一个GPU上

In [12]:
net[0].weight.data.device

device(type='cuda', index=0)