In [1]:
import torch

标量只由一个元素的张量表示

In [2]:
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x-y,x*y,x/y

(tensor([5.]), tensor([1.]), tensor([6.]), tensor([1.5000]))

你可以将向量视为标量值组成的列表

In [3]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [4]:
x[3]

tensor(3)

访问张量的长度

In [5]:
len(x)

4

只有一个轴的张量，形状只有一个元素

In [6]:
x.shape

torch.Size([4])

通过指定两个分量m和n来创建一个形状为m*n的矩阵

In [7]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵A等于其转置

In [10]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

我们可以构建具有更多轴的数据结构

In [12]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定任何相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [13]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() # 通过分配新内存，将A的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为哈达玛积

In [14]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [16]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape,a*X

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

计算其元素和

In [17]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [25]:
A.shape,A.sum(),A.sum(axis=1),X.sum(axis=[1,2])

(torch.Size([5, 4]),
 tensor(190.),
 tensor([ 6., 22., 38., 54., 70.]),
 tensor([ 66, 210]))

一个与求和相关的量是平均值(mean和average)

In [26]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [27]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

计算总和或均值时保持轴数不变

In [30]:
sum_A=A.sum(axis=1,keepdims=True)
A.sum(axis=1),sum_A

(tensor([ 6., 22., 38., 54., 70.]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]))

通过广播将A除以sum_A

In [31]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

点积是相同位置的按元素乘积的和

In [32]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [33]:
torch.sum(x*y)

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量

In [34]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积

In [35]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

范数即矩阵或向量的长度，L2范数是向量元素平方和的平方根

In [36]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数表示向量元素的绝对值之和

In [37]:
torch.abs(u).sum()

tensor(7.)

矩阵的佛罗贝尼乌斯范数是矩阵元素的平方和的平方根

In [39]:
torch.norm(torch.ones((4,9)))

tensor(6.)