构造一个没有任何参数的自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self,X):
    return X-X.mean()
  
layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [2]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y=net(torch.rand(4,8))
Y.mean()

tensor(4.6566e-09, grad_fn=<MeanBackward0>)

带参数的图层

In [3]:
class MyLinear(nn.Module):
  def __init__(self,in_units,units):
    super().__init__()
    self.weight=nn.Parameter(torch.randn(in_units,units))
    self.bias=nn.Parameter(torch.randn(units,))
  
  def forward(self,X):
    linear=torch.matmul(X,self.weight.data)+self.bias.data
    return F.relu(linear)

dense=MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[ 0.3537,  1.2581,  1.1359],
        [ 1.8705, -1.1480,  2.4796],
        [-1.3282,  0.3953,  0.2980],
        [ 2.1509,  0.7727,  1.1335],
        [ 0.1002, -0.9331,  2.4641]], requires_grad=True)

使用自定义层直接执行正向传播计算

In [4]:
dense(torch.rand(2,5))

tensor([[2.2326, 0.0000, 2.8426],
        [1.7489, 0.1799, 2.3966]])

使用自定义层构建模型

In [6]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[11.0102],
        [10.5980]])